### ISSUE TITLE
the examples use <name>_jll but how do you generate <name>_jll ?

### ISSUE THREAD

**Issue by PinkMushroom** [analytech-solutions/ExamplesUsingC.jl#2]

**Comment by PinkMushroom** [comment]
you need assimp_jll, libsdl2_jll, etc... but i don't know how you actually generate them.

i've noticed that they exist as julia packages, well at least SDL2_jll, does but it's not obvious how you go about making them if you are creating new c bindings.

**Comment by krrutkow** [comment]
I'm not exactly sure what you are asking, but those packages are downloaded when you run the package tests `] test ExamplesUsingCBinding` so you don't need to generate them.

If you are wondering how to create those types of packages yourself, then look for documentation related to creating artifacts (`*_jll` packages) which is covered with [Pkg.jl docs](https://pkgdocs.julialang.org/v1/artifacts/) and [BinaryBuilder.jl docs](https://docs.binarybuilder.org/stable/).

Also, the binaries you want to create new bindings to could be part of your Linux distribution or software you build yourself, etc.  It doesn't really matter how you obtain the libraries and header files, though, the CBinding.jl usage will be practically the same except for the particular paths used.  You could look at [System.jl](https://github.com/analytech-solutions/System.jl/tree/master/pkgs) for examples of interfacing to system software, or [PLCTag.jl](https://github.com/libplctag/PLCTag.jl/blob/master/deps/build.jl) for an example of downloading a library and building it as part of the package build process.

**Comment by PinkMushroom** [comment]
> If you are wondering how to create those types of packages yourself

yes, that's what i was trying to figure out.

since your examples needed them, I couldn't quite decide if CBinding was generating them somehow in a "pre-process" step of some sort.

thank you !
